### ISSUE TITLE
Mixed content : http and https

### ISSUE THREAD

**Issue by hritikrommie** [hritikrommie/Weather-forecast#1]
Error Message

app.js:24 Mixed Content: The page at 'https://hritikrommie.github.io/Weather-forecast/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://dataservice.accuweather.com/locations/v1/cities/search?apikey=lJv1VKjEIAG5uHkz68hsktmQeP0i5Abx&q=Bhopal'. This request has been blocked; the content must be served over HTTPS.

**Comment by bklynate** [comment]
You can assign this ticket to me

Update: PR Raised

**Comment by hritikrommie** [comment]
Thanks! It worked. :)
